export const metadata = {
  title: 'Блог',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <section>
      {children}
      <div className="blog-page__sidebar">
        <div className="filter">
          <h2>Рубрики</h2>
          <ul>
            <li>
              <span>Все публикации</span> <span>123</span>
            </li>
            <li>
              <span>Новости</span> <span>34</span>
            </li>
            <li>
              <span>Статьи</span> <span>99</span>
            </li>
            <li>
              <span>Советы</span> <span>14</span>
            </li>
            <li>
              <span>Обзоры</span> <span>2</span>
            </li>
          </ul>
        </div>
        <article>
          <h3>Подпишитесь на рассылку</h3>
          <p>Регулярные скидки и спецпредложения, а так же новости компании.</p>
          <form>
            <input type="email" />
            <button type="submit">Подписаться</button>
            <small>
              Согласен с{' '}
              <a href="/privacy-policy">политикой конфиденциальности</a>
            </small>
          </form>
        </article>
      </div>
    </section>
  );
}
